version: '2'

services:
   db:
     image: mariadb:10.4.10     
     environment:
       MYSQL_ROOT_PASSWORD: root!
       MYSQL_DATABASE: yourapp
       MYSQL_USER: yourapp
       MYSQL_PASSWORD: yourapp!
     ports:
       - "3306:3306"          
     volumes:
       - mysql_data:/var/lib/mysql
     restart: always       
   yourapp:
     image: songgolmae/yourapp
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
     ports:
      - "80:80"
      #- "443:443"
     volumes: 
      - app_data:/app      
     depends_on:
       - db      
     restart: always
volumes:
    mysql_data: {}
    app_data: {}
    
