version: '3.3'

services:
   db:
     image: mariadb
     volumes:
       - db_data:/var/lib/mysql   
     restart: always
     ports:
       - "3306:3306"     
     environment:
       MYSQL_ROOT_PASSWORD: root!
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   yourapp:
     depends_on:
       - db
     image: songgolmae/yourapp
     #volumes: ['~/app/:/app']
     ports:
       - "5000:80"
       - "5001:443"
     restart: always
     #environment:
     #  YOURAPP_DB_HOST: db:3306
     #  YOURAPP_DB_USER: yourapp
     #  YOURAPP_DB_PASSWORD: yourapp
     #  YOURAPP_DB_NAME: yourapp
volumes:
    db_data: {}
    #wordpress: {}
