version: '2'

services:
  web:
    image: songgolmae/my-blazor-first-sample
    container_name: my-blazor-first-sample
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
    - "80:80"
    - "443:443"
    volumes: 
    - app_data:/app      
volumes:
  app_data: 
    driver: local
