version: '3.4'

services:
   db:
     image: mariadb
     volumes:
       - db_data:/var/lib/mysql   
     restart: always
     ports:
       - "3306:3306"     
     environment:
       MYSQL_ROOT_PASSWORD: root!
       MYSQL_DATABASE: yourapp
       MYSQL_USER: yourapp
       MYSQL_PASSWORD: yourapp
   yourapp:
     depends_on:
       - db
     image: songgolmae/yourapp
     #volumes: ['~/app/:/app']
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
     ports:
      - "80"
      - "443"
     restart: always
volumes:
    db_data: {}
    #wordpress: {}
