version: '2'

services:
  web:
    image: songgolmae/myblazorfirstsample
    container_name: myblazorfirstsample
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
    - "80:80"
    - "443:443"
    volumes: 
    - app_data:/myblazorfirstsample      
volumes:
  app_data: 
    driver: local
